name: CI (Test Runner)

on:
  push:
    branches: [ "main", "feature/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    # 👇 [추가된 부분] 깃허브야, 몽고DB 서비스 좀 켜줘!
    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint

    - name: Build project
      run: npm run build

    # 👇 [추가된 부분] 테스트할 때 환경변수(DB 주소) 알려주기
    - name: Run Tests
      run: npm run test
      env:
        # 깃허브에선 localhost:27017로 접속하면 위에서 만든 DB 연결
        MONGO_URI: mongodb://localhost:27017/test
        PORT: 3000
        NODE_ENV: test